/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;



import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;


public class AppTest {

    private App businessLogic;

    @BeforeEach
    public void setUp() {
        businessLogic = new App();
    }

    // Unit test for sum method
    @Test
    public void testSum() {
        assertEquals(5, businessLogic.sum(2, 3));
        assertEquals(0, businessLogic.sum(-5, 5));
    }

    // Unit test for isPalindrome method
    @Test
    public void testIsPalindrome() {
        assertTrue(businessLogic.isPalindrome("madam"));
        assertFalse(businessLogic.isPalindrome("hello"));
    }

    // Unit test for factorial method
    @Test
    public void testFactorial() {
        assertEquals(120, businessLogic.factorial(5));
        assertEquals(1, businessLogic.factorial(0));
    }

    // Unit test for findMax method
    @Test
    public void testFindMax() {
        int[] array = {1, 2, 3, 4, 5};
        assertEquals(5, businessLogic.findMax(array));
    }

    // Unit test for toUpperCase method
    @Test
    public void testToUpperCase() {
        assertEquals("HELLO", businessLogic.toUpperCase("hello"));
        assertEquals("WORLD", businessLogic.toUpperCase("world"));
    }
}
